namespace Am.Tests {

    class ExceptionTests {
        import Am.Lang
        import Am.Collections
        import Am.Testing
        
        static test throwAndCatch() {
            var caught = false
            try {
                throw new Exception("Test exception")
            } catch(e: Exception) {
                caught = true
            }
            
            Assert.assertTrue(caught)
        }
        
        static test exceptionMessage() {
            var message = ""
            try {
                throw new Exception("Custom message")
            } catch(e: Exception) {
                message = e.getMessage()
            }
            
            Assert.assertEquals("Custom message", message)
        }
        
        static test listIndexOutOfBounds() {
            var caught = false
            var list = List.newList<Int>()
            list.add(1)
            
            try {
                var item = list.get(10)  // Index out of bounds
            } catch(e: Exception) {
                caught = true
            }
            
            Assert.assertTrue(caught)
        }
    }
}
